#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
bridge_mqtt.py – Python bridge for the UNO Q measure rig

This script runs on the Linux side of an Arduino UNO Q board and
coordinates communication between the microcontroller sketch and an
MQTT broker.  It listens for raw measurement data from the MCU via the
Router Bridge RPC interface, computes box dimensions from the raw
distances, and publishes JSON payloads to MQTT.  It also subscribes
to a command topic and forwards capture requests back to the MCU.

Environment variables control the broker address, credentials and
reference distances used for calculating the box size:

• ``MQTT_BROKER`` – hostname or IP address of the MQTT server (default
  ``10.1.1.85``)
• ``MQTT_PORT``  – port number of the MQTT server (default ``1883``)
• ``MQTT_USER`` / ``MQTT_PASS`` – optional username/password for
  authenticated brokers
• ``MQTT_CMD_TOPIC`` – topic to listen for capture commands
  (default ``measure/cmd``)
• ``MQTT_DATA_TOPIC`` – topic to publish measurement data to
  (default ``measure/data``)
• ``MQTT_LOG_TOPIC`` – topic to publish log messages to (default
  ``measure/log``)
• ``MQTT_CLIENT_ID`` – MQTT client identifier (default ``uno-q-bridge``)
• ``REF_LENGTH_CM``, ``REF_HEIGHT_CM``, ``REF_WIDTH_CM`` – reference
distances, in centimetres, measured from each sensor to the back wall
  with no box present (defaults mirror the UNO R4 sketch values)
• ``SERIAL_SCALE_PORT`` – serial port for the external scale
  (default ``/dev/ttyUSB0``)
• ``SERIAL_SCALE_BAUDRATE`` – baud rate for the serial scale
  (default ``9600``)
• ``ENABLE_SERIAL_SCALE`` – enable the serial scale reader
  (default ``true``)
• ``SERIAL_SCALE_RECONNECT_DELAY`` – seconds between reconnect attempts
  (default ``3``)

The script registers the following bridge functions for use by the
microcontroller sketch:

• ``linux_started`` – returns ``True`` to signal the MCU that the
  Python environment is ready.  The sketch polls this function during
  its setup routine before proceeding.
• ``mcu_ready`` – called by the sketch when it has finished its setup
  routine.  The function simply logs that the MCU is ready.
• ``measurement_data`` – invoked by the sketch via ``Bridge.notify``
  with three arguments: ``height_raw``, ``width_raw`` and
  ``length_raw`` (in centimetres).  The handler computes box
dimensions, assembles a JSON payload and publishes it to
  ``MQTT_DATA_TOPIC``.

Upon receiving a message on ``MQTT_CMD_TOPIC`` containing the word
``CAP``, ``CAPTURE`` or ``CAPTUR`` (case‑insensitive), the script
issues an RPC call to the microcontroller’s ``capture`` function to
initiate a new measurement.  Any log messages generated by this script
are also sent to ``MQTT_LOG_TOPIC`` when the client is connected.

Version: Ver-2601110900
"""

import json
import math
import os
import re
import threading
import time
from typing import Optional

import paho.mqtt.client as mqtt
from arduino.app_utils import Bridge, App

from collections import deque
import html
import serial

# ─── Configuration ─────────────────────────────────────────

def _get_int_env(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return int(raw)
    except (TypeError, ValueError):
        _log(f"[CONFIG] Invalid value for {name}='{raw}', using default {default}.")
        return default


def _get_float_env(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return float(raw)
    except (TypeError, ValueError):
        _log(f"[CONFIG] Invalid value for {name}='{raw}', using default {default}.")
        return default

MQTT_BROKER = os.getenv("MQTT_BROKER", "10.1.1.85")
MQTT_PORT = _get_int_env("MQTT_PORT", 1883)
MQTT_USER = os.getenv("MQTT_USER")
MQTT_PASS = os.getenv("MQTT_PASS")

MQTT_CMD_TOPIC = os.getenv("MQTT_CMD_TOPIC", "measure/cmd")
MQTT_DATA_TOPIC = os.getenv("MQTT_DATA_TOPIC", "measure/data")
MQTT_LOG_TOPIC = os.getenv("MQTT_LOG_TOPIC", "measure/log")
MQTT_CLIENT_ID = os.getenv("MQTT_CLIENT_ID", "uno-q-bridge")

REF_LENGTH_CM = _get_float_env("REF_LENGTH_CM", 80.0)
REF_HEIGHT_CM = _get_float_env("REF_HEIGHT_CM", 89.0)
REF_WIDTH_CM = _get_float_env("REF_WIDTH_CM", 70.0)

SERIAL_SCALE_PORT = os.getenv("SERIAL_SCALE_PORT", "/dev/ttyUSB0")
SERIAL_SCALE_BAUDRATE = _get_int_env("SERIAL_SCALE_BAUDRATE", 9600)
SERIAL_SCALE_ENABLED = os.getenv("ENABLE_SERIAL_SCALE", "true").lower() not in (
    "0",
    "false",
    "no",
)
SERIAL_SCALE_RECONNECT_DELAY = _get_int_env("SERIAL_SCALE_RECONNECT_DELAY", 3)

mqtt_client = mqtt.Client(client_id=MQTT_CLIENT_ID, protocol=mqtt.MQTTv311)

if MQTT_USER:
    if MQTT_PASS is not None:
        mqtt_client.username_pw_set(MQTT_USER, MQTT_PASS)
    else:
        mqtt_client.username_pw_set(MQTT_USER)

_log_lock = threading.Lock()
_log_buffer: deque[str] = deque()
_serial_scale_lock = threading.Lock()
_serial_scale_thread: Optional[threading.Thread] = None
_cached_serial_weight: Optional[float] = None
_cached_serial_weight_timestamp: Optional[float] = None


def _sanitize_log(msg: str) -> str:
    """Sanitize a log message before printing/publishing.

    Replaces newline and carriage return characters with spaces and escapes
    angle brackets to prevent log injection or HTML/script injection when
    consumed by a dashboard. Non‑printable characters are also replaced with a space.
    """
    # Ensure message is str
    msg_str = str(msg)
    # Escape HTML special characters
    escaped = html.escape(msg_str)
    # Replace CR and LF with space and remove non-printable characters
    sanitized_chars = []
    for ch in escaped:
        if ch in '\n\r' or not ch.isprintable():
            sanitized_chars.append(' ')
        else:
            sanitized_chars.append(ch)
    return ''.join(sanitized_chars)


def _log(msg: str) -> None:
    msg = _sanitize_log(str(msg))
    print(msg)
    with _log_lock:
        _log_buffer.append(msg)


def _flush_log() -> None:
    if not mqtt_client.is_connected():
        with _log_lock:
            _log_buffer.clear()
        return
    with _log_lock:
        while _log_buffer:
            line = _log_buffer.popleft()
            try:
                mqtt_client.publish(MQTT_LOG_TOPIC, line, qos=0, retain=False)
            except Exception:
                _log_buffer.appendleft(line)
                break


def _on_mqtt_connect(client, userdata, flags, rc, properties=None):
    if rc == 0:
        _log(f"[MQTT] Connected to {MQTT_BROKER}:{MQTT_PORT} as {MQTT_CLIENT_ID}.")
        client.subscribe(MQTT_CMD_TOPIC)
        _log(f"[MQTT] Subscribed to command topic '{MQTT_CMD_TOPIC}'.")
    else:
        _log(f"[MQTT] Connection failed with code {rc}.")


def _on_mqtt_disconnect(client, userdata, rc, properties=None):
    if rc != 0:
        _log(f"[MQTT] Unexpected disconnect (rc={rc}). Will retry automatically.")


def _on_mqtt_message(client, userdata, msg):
    try:
        payload = msg.payload.decode("utf-8", errors="replace").strip()
    except Exception:
        payload = repr(msg.payload)
    _log(f"[MQTT] Received message on '{msg.topic}': {payload}")
    if msg.topic != MQTT_CMD_TOPIC:
        return
    if payload.lower().startswith("cap"):
        _log("[BRIDGE] Capture command received via MQTT. Invoking MCU 'capture' function…")
        try:
            bridge.call("capture")
        except Exception as e:
            _log(f"[BRIDGE] Error invoking 'capture': {e}")


mqtt_client.on_connect = _on_mqtt_connect
mqtt_client.on_disconnect = _on_mqtt_disconnect
mqtt_client.on_message = _on_mqtt_message

bridge = Bridge()

def linux_started() -> bool:
    return True

def mcu_ready() -> None:
    _log("[BRIDGE] MCU signalled it is ready.")

def _safe_float(value) -> Optional[float]:
    try:
        if value is None:
            return None
        return float(value)
    except (TypeError, ValueError):
        return None

def _box_dim_from_raw(ref_cm: float, raw: Optional[float]) -> Optional[float]:
    if raw is None or not math.isfinite(raw):
        return None
    box = ref_cm - raw
    return max(box, 0.0)

def _parse_serial_scale_line(line: str) -> Optional[float]:
    if not isinstance(line, str):
        return None
    match = re.search(r"([-+]?\d+(?:\.\d+)?)", line)
    if not match:
        return None
    return _safe_float(match.group(1))

def _apply_serial_scale_weight(weight_value, source_line: Optional[str] = None) -> None:
    if not isinstance(weight_value, (int, float)):
        return
    weight_float = float(weight_value)
    timestamp = time.time()
    with _serial_scale_lock:
        global _cached_serial_weight, _cached_serial_weight_timestamp
        _cached_serial_weight = weight_float
        _cached_serial_weight_timestamp = timestamp
    if source_line:
        _log(f"[SERIAL-SCALE] Weight {weight_float:.3f} parsed from line: '{source_line}'")
    else:
        _log(f"[SERIAL-SCALE] Weight {weight_float:.3f} received from serial scale.")

def _serial_scale_reader_loop() -> None:
    if not SERIAL_SCALE_PORT:
        _log("[SERIAL-SCALE] SERIAL_SCALE_PORT is not configured; skipping serial scale reader.")
        return
    _log(
        f"[SERIAL-SCALE] Starting reader on {SERIAL_SCALE_PORT} at {SERIAL_SCALE_BAUDRATE} baud..."
    )
    while True:
        try:
            with serial.Serial(SERIAL_SCALE_PORT, SERIAL_SCALE_BAUDRATE, timeout=1) as ser:
                _log(
                    f"[SERIAL-SCALE] Connected to {SERIAL_SCALE_PORT}. Listening for weight data..."
                )
                while True:
                    line_bytes = ser.readline()
                    if not line_bytes:
                        continue
                    try:
                        decoded = line_bytes.decode("utf-8", errors="ignore").strip()
                    except Exception as exc:
                        _log(f"[SERIAL-SCALE] Failed to decode serial data: {exc}")
                        continue
                    if not decoded:
                        continue
                    weight_val = _parse_serial_scale_line(decoded)
                    if weight_val is None:
                        continue
                    _apply_serial_scale_weight(weight_val, decoded)
        except serial.SerialException as exc:
            _log(
                f"[SERIAL-SCALE] Serial exception on {SERIAL_SCALE_PORT}: {exc}. "
                f"Reconnecting in {SERIAL_SCALE_RECONNECT_DELAY}s..."
            )
            time.sleep(SERIAL_SCALE_RECONNECT_DELAY)
        except Exception as exc:
            _log(
                f"[SERIAL-SCALE] Unexpected error while reading from {SERIAL_SCALE_PORT}: {exc}. "
                f"Reconnecting in {SERIAL_SCALE_RECONNECT_DELAY}s..."
            )
            time.sleep(SERIAL_SCALE_RECONNECT_DELAY)

def _start_serial_scale_reader_thread() -> None:
    global _serial_scale_thread
    if not SERIAL_SCALE_ENABLED:
        _log("[SERIAL-SCALE] Serial scale reader disabled via ENABLE_SERIAL_SCALE flag.")
        return
    if _serial_scale_thread and _serial_scale_thread.is_alive():
        return
    _serial_scale_thread = threading.Thread(
        target=_serial_scale_reader_loop, name="SerialScaleReader", daemon=True
    )
    _serial_scale_thread.start()

def measurement_data(height_raw, width_raw, length_raw) -> None:
    h_raw = _safe_float(height_raw)
    w_raw = _safe_float(width_raw)
    l_raw = _safe_float(length_raw)
    h_box = _box_dim_from_raw(REF_HEIGHT_CM, h_raw)
    w_box = _box_dim_from_raw(REF_WIDTH_CM, w_raw)
    l_box = _box_dim_from_raw(REF_LENGTH_CM, l_raw)
    dims = [d for d in (h_box, w_box, l_box) if isinstance(d, float)]
    dimension_max = max(dims) if dims else None
    payload = {
        "height": h_box,
        "width": w_box,
        "length": l_box,
        "dimension": dimension_max,
        "height_raw": h_raw,
        "width_raw": w_raw,
        "length_raw": l_raw,
        "height_box": h_box,
        "width_box": w_box,
        "length_box": l_box,
    }
    with _serial_scale_lock:
        cached_weight = _cached_serial_weight
        cached_weight_ts = _cached_serial_weight_timestamp
    if cached_weight is not None:
        payload.update(
            {
                "weight": cached_weight,
                "weight_net": cached_weight,
                "weight_gross": cached_weight,
                "weight_timestamp": cached_weight_ts,
                "weight_source": "serial_scale",
                "scale_present": True,
                "serial_scale_port": SERIAL_SCALE_PORT,
            }
        )
    try:
        mqtt_client.publish(MQTT_DATA_TOPIC, json.dumps(payload), qos=0, retain=False)
        _log("[MQTT] Published measurement payload.")
    except Exception as e:
        _log(f"[MQTT] Failed to publish measurement: {e}")

bridge.provide("linux_started", linux_started)
bridge.provide("mcu_ready", mcu_ready)
bridge.provide("measurement_data", measurement_data)

def _start_mqtt():
    try:
        mqtt_client.connect(MQTT_BROKER, MQTT_PORT, keepalive=60)
        mqtt_client.loop_start()
    except Exception as e:
        _log(f"[MQTT] Failed to connect to broker at {MQTT_BROKER}:{MQTT_PORT}: {e}")

def _user_loop() -> None:
    _flush_log()
    time.sleep(0.1)

def main() -> None:
    _log("[SYSTEM] UNO Q MQTT bridge starting…")
    _start_mqtt()
    _start_serial_scale_reader_thread()
    App.run(user_loop=_user_loop)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        _log("[SYSTEM] Shutdown requested by user (Ctrl‑C).")
    except Exception as exc:
        _log(f"[ERROR] Unhandled exception: {exc}")
    finally:
        try:
            mqtt_client.loop_stop()
            mqtt_client.disconnect()
        except Exception:
            pass
        _flush_log()
        _log("[SYSTEM] Bridge script terminated.")
