#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
bridge_mqtt.py – Python bridge for the UNO Q measure rig

This script runs on the Linux side of an Arduino UNO Q board and
coordinates communication between the microcontroller sketch and an
MQTT broker.  It listens for raw measurement data from the MCU via the
Router Bridge RPC interface, computes box dimensions from the raw
distances, and publishes JSON payloads to MQTT.  It also subscribes
to a command topic and forwards capture requests back to the MCU.

Environment variables control the broker address, credentials and
reference distances used for calculating the box size:

• ``MQTT_BROKER`` – hostname or IP address of the MQTT server (default
  ``10.1.1.85``)
• ``MQTT_PORT``  – port number of the MQTT server (default ``1883``)
• ``MQTT_USER`` / ``MQTT_PASS`` – optional username/password for
  authenticated brokers
• ``MQTT_CMD_TOPIC`` – topic to listen for capture commands
  (default ``measure/cmd``)
• ``MQTT_DATA_TOPIC`` – topic to publish measurement data to
  (default ``measure/data``)
• ``MQTT_LOG_TOPIC`` – topic to publish log messages to (default
  ``measure/log``)
• ``MQTT_CLIENT_ID`` – MQTT client identifier (default ``uno-q-bridge``)
• ``REF_LENGTH_CM``, ``REF_HEIGHT_CM``, ``REF_WIDTH_CM`` – reference
  distances, in centimetres, measured from each sensor to the back wall
  with no box present (defaults mirror the UNO R4 sketch values)

The script registers the following bridge functions for use by the
microcontroller sketch:

• ``linux_started`` – returns ``True`` to signal the MCU that the
  Python environment is ready.  The sketch polls this function during
  its setup routine before proceeding.
• ``mcu_ready`` – called by the sketch when it has finished its setup
  routine.  The function simply logs that the MCU is ready.
• ``measurement_data`` – invoked by the sketch via ``Bridge.notify``
  with three arguments: ``height_raw``, ``width_raw`` and
  ``length_raw`` (in centimetres).  The handler computes box
  dimensions, assembles a JSON payload and publishes it to
  ``MQTT_DATA_TOPIC``.

Upon receiving a message on ``MQTT_CMD_TOPIC`` containing the word
``CAP``, ``CAPTURE`` or ``CAPTUR`` (case‑insensitive), the script
issues an RPC call to the microcontroller’s ``capture`` function to
initiate a new measurement.  Any log messages generated by this script
are also sent to ``MQTT_LOG_TOPIC`` when the client is connected.

Version: Ver-2601110900
"""

import json
import math
import os
import threading
import time
from typing import Optional

import paho.mqtt.client as mqtt
from arduino.app_utils import Bridge, App

from collections import deque

# ─── Configuration ───────────────────────────────────────────────────────

def _get_int_env(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return int(raw)
    except (TypeError, ValueError):
        _log(f"[CONFIG] Invalid value for {name}='{raw}', using default {default}.")
        return default


def _get_float_env(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return float(raw)
    except (TypeError, ValueError):
        _log(f"[CONFIG] Invalid value for {name}='{raw}', using default {default}.")
        return default

MQTT_BROKER = os.getenv("MQTT_BROKER", "10.1.1.85")
MQTT_PORT = _get_int_env("MQTT_PORT", 1883)
MQTT_USER = os.getenv("MQTT_USER")
MQTT_PASS = os.getenv("MQTT_PASS")

MQTT_CMD_TOPIC = os.getenv("MQTT_CMD_TOPIC", "measure/cmd")
MQTT_DATA_TOPIC = os.getenv("MQTT_DATA_TOPIC", "measure/data")
MQTT_LOG_TOPIC = os.getenv("MQTT_LOG_TOPIC", "measure/log")
MQTT_CLIENT_ID = os.getenv("MQTT_CLIENT_ID", "uno-q-bridge")

REF_LENGTH_CM = _get_float_env("REF_LENGTH_CM", 80.0)
REF_HEIGHT_CM = _get_float_env("REF_HEIGHT_CM", 89.0)
REF_WIDTH_CM = _get_float_env("REF_WIDTH_CM", 70.0)

mqtt_client = mqtt.Client(client_id=MQTT_CLIENT_ID, protocol=mqtt.MQTTv311)

if MQTT_USER:
    if MQTT_PASS is not None:
        mqtt_client.username_pw_set(MQTT_USER, MQTT_PASS)
    else:
        mqtt_client.username_pw_set(MQTT_USER)

_log_lock = threading.Lock()
_log_buffer: deque[str] = deque()


def _sanitize_log(msg: str) -> str:
    # Replace newlines and carriage returns to avoid log injection; collapse control chars
    return ''.join(c if c.isprintable() and c not in '\n\r' else ' ' for c in msg)


def _log(msg: str) -> None:
    msg = _sanitize_log(str(msg))
    print(msg)
    with _log_lock:
        _log_buffer.append(msg)


def _flush_log() -> None:
    if not mqtt_client.is_connected():
        with _log_lock:
            _log_buffer.clear()
        return
    with _log_lock:
        while _log_buffer:
            line = _log_buffer.popleft()
            try:
                mqtt_client.publish(MQTT_LOG_TOPIC, line, qos=0, retain=False)
            except Exception:
                _log_buffer.appendleft(line)
                break


def _on_mqtt_connect(client, userdata, flags, rc, properties=None):
    if rc == 0:
        _log(f"[MQTT] Connected to {MQTT_BROKER}:{MQTT_PORT} as {MQTT_CLIENT_ID}.")
        client.subscribe(MQTT_CMD_TOPIC)
        _log(f"[MQTT] Subscribed to command topic '{MQTT_CMD_TOPIC}'.")
    else:
        _log(f"[MQTT] Connection failed with code {rc}.")


def _on_mqtt_disconnect(client, userdata, rc, properties=None):
    if rc != 0:
        _log(f"[MQTT] Unexpected disconnect (rc={rc}). Will retry automatically.")


def _on_mqtt_message(client, userdata, msg):
    try:
        payload = msg.payload.decode("utf-8", errors="replace").strip()
    except Exception:
        payload = repr(msg.payload)
    _log(f"[MQTT] Received message on '{msg.topic}': {payload}")
    if msg.topic != MQTT_CMD_TOPIC:
        return
    if payload.lower().startswith("cap"):
        _log("[BRIDGE] Capture command received via MQTT. Invoking MCU 'capture' function…")
        try:
            bridge.call("capture")
        except Exception as e:
            _log(f"[BRIDGE] Error invoking 'capture': {e}")


mqtt_client.on_connect = _on_mqtt_connect
mqtt_client.on_disconnect = _on_mqtt_disconnect
mqtt_client.on_message = _on_mqtt_message

bridge = Bridge()

def linux_started() -> bool:
    return True

def mcu_ready() -> None:
    _log("[BRIDGE] MCU signalled it is ready.")

def _safe_float(value) -> Optional[float]:
    try:
        if value is None:
            return None
        return float(value)
    except (TypeError, ValueError):
        return None

def _box_dim_from_raw(ref_cm: float, raw: Optional[float]) -> Optional[float]:
    if raw is None or not math.isfinite(raw):
        return None
    box = ref_cm - raw
    return max(box, 0.0)

def measurement_data(height_raw, width_raw, length_raw) -> None:
    h_raw = _safe_float(height_raw)
    w_raw = _safe_float(width_raw)
    l_raw = _safe_float(length_raw)
    h_box = _box_dim_from_raw(REF_HEIGHT_CM, h_raw)
    w_box = _box_dim_from_raw(REF_WIDTH_CM, w_raw)
    l_box = _box_dim_from_raw(REF_LENGTH_CM, l_raw)
    dims = [d for d in (h_box, w_box, l_box) if isinstance(d, float)]
    dimension_max = max(dims) if dims else None
    payload = {
        "height": h_box,
        "width": w_box,
        "length": l_box,
        "dimension": dimension_max,
        "height_raw": h_raw,
        "width_raw": w_raw,
        "length_raw": l_raw,
        "height_box": h_box,
        "width_box": w_box,
        "length_box": l_box,
    }
    try:
        mqtt_client.publish(MQTT_DATA_TOPIC, json.dumps(payload), qos=0, retain=False)
        _log("[MQTT] Published measurement payload.")
    except Exception as e:
        _log(f"[MQTT] Failed to publish measurement: {e}")

bridge.provide("linux_started", linux_started)
bridge.provide("mcu_ready", mcu_ready)
bridge.provide("measurement_data", measurement_data)

def _start_mqtt():
    try:
        mqtt_client.connect(MQTT_BROKER, MQTT_PORT, keepalive=60)
        mqtt_client.loop_start()
    except Exception as e:
        _log(f"[MQTT] Failed to connect to broker at {MQTT_BROKER}:{MQTT_PORT}: {e}")

def _user_loop() -> None:
    _flush_log()
    time.sleep(0.1)

def main() -> None:
    _log("[SYSTEM] UNO Q MQTT bridge starting…")
    _start_mqtt()
    App.run(user_loop=_user_loop)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        _log("[SYSTEM] Shutdown requested by user (Ctrl‑C).")
    except Exception as exc:
        _log(f"[ERROR] Unhandled exception: {exc}")
    finally:
        try:
            mqtt_client.loop_stop()
            mqtt_client.disconnect()
        except Exception:
            pass
        _flush_log()
        _log("[SYSTEM] Bridge script terminated.")
